name: 'Deploy backend code to Render.com'

on:
  push:
    branches: 
      - main
    paths:
      - 'app/**'
  
  pull_request:
    branches: 
      - main
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          SERVICE_KEY: ${{ secrets.RENDER_BACKEND_SERVICE_KEY }}
        run: |
          DEPLOY_URL="https://api.render.com/deploy/${SERVICE_ID}?key=${SERVICE_KEY}"
          
          echo "Deploying backend service ID: ${SERVICE_ID}"
          
          curl -X POST "$DEPLOY_URL"