name: 'Deploy frontend code to Render.com'

on:
  push:
    branches: 
      - main
    paths:
      - 'client/**'
  
  pull_request:
    branches: 
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}
        run: |
          set -x  # Enable verbose output
          echo "Deploying frontend..."
          
          # Print the raw URL
          echo "Raw URL: $deploy_url"
          echo "URL length: ${#deploy_url}"
          
          # Trim whitespace and use printf to reveal potential hidden characters
          trimmed_url=$(printf '%s' "$deploy_url" | xargs)
          
          echo "Trimmed URL: $trimmed_url"
          echo "Trimmed URL length: ${#trimmed_url}"
          
          # Use verbose curl to see exact details
          curl -v -L "$trimmed_url"
