name: 'Deploy frontend code to Render.com'

on:
  push:
    branches: 
      - main
    paths:
      - 'client/**'
  
  pull_request:
    branches: 
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          SERVICE_ID: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          SERVICE_KEY: ${{ secrets.RENDER_FRONTEND_SERVICE_KEY }}
        run: |
          DEPLOY_URL="https://api.render.com/deploy/${SERVICE_ID}?key=${SERVICE_KEY}"
          
          echo "Deploying frontend service ID: ${SERVICE_ID}"
          
          curl -X POST "$DEPLOY_URL"